# Generated by Django 5.2.3 on 2025-07-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
